1st commit

diff --git a/.github/workflows/Env.yml b/.github/workflows/Env.yml
--- a/.github/workflows/Env.yml
+++ b/.github/workflows/Env.yml
@@ -1,36 +1,53 @@
-# This is a basic workflow to help you get started with Actions
-
-name: CI
+name: Work Flow Based On Different Env
 
 # Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+ workflow_dispatch:
+  inputs:
+    Enviroment:
+      Description: "Which Env to deploy e.g. dev,uat"
+      required: true
+      type: choice
+      option: 
+        - dev
+        - uat
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+
+  Terraform_action_build:
+
+    name: Terraform_action_build
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - name: checkout_actions
       - uses: actions/checkout@v4
+      - name: set up terraform hasicorp 
+      - uses: hashicorp/setup-terraform@v1
 
+        with:
+          terraform_version: 1.1.7
+
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: $aws_region
       # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Terrform init
+        run: | 
+          cd module
+          terraform init
+        
+      - name: checking env condition where to depoy
+        id: determine_tfvars
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if [ "${{ github.event.input.enviroment }}" = "dev"]; then
+            echo "TFVAR_FILE=dev.tfvars" >> $GITHUB_ENV
+          elif [ "${{ github.event.inputs.enviroment }}" = "uat"]; then
+            echo "TFVAR_FILE=uat.tfvars" >> $GITHUB_ENV
+          else
+            echo "Error: Unsupported enviroment"
+            exit 1
+          fi
+
